const BLUENUMBER = 10                                                         #Number of blues
const GREENNUMBER = 10
const ORANGENUMBER = 10
const PURPLENUMBER = 10
const REDNUMBER = 10                                                          #Number of reds
const YELLOWNUMBER = 10
const RADIUS = 5                                                             #Dot radius
const RANGE = 150
const SCREENSIZE = Vector2(1500, 800)                                        #Size of the screen
const SENSITIVITY = 0.06
